version: 2.1
jobs:
  pull:
    steps:
      - add_ssh_keys
      - run:
          name: known_hosts sadness
          command: ssh-keyscan -H $SITE_SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: pull
          command: ssh "$SITE_SSH_USER@$SITE_SSH_HOST" "cd /var/www/conf && git pull"

workflows:
  version: 2.1
  just-pull-new-stuff:
    jobs:
      - pull:
          filters:
            branches:
              only:
                - master
